apiVersion: v1
kind: Service
metadata:
  name: web
  labels:
    service: web
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    service: web
  # {{ if .Values.nodeport }}
  # type: NodePort
  # {{ else }}
  type: ClusterIP
  # {{ end }}
---
{{if .Values.ocCreateRoute}}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: web
spec:
  to:
    kind: Service
    name: web
{{ else }}
apiVersion: networking.k8s.io/v1beta1
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: web
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
    # cert-manager.io/issuer: letsencrypt-prod
    # kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: robot-dev.k8s.kositech.com.hk
    http:
      paths:
      - backend:
          serviceName: web
          servicePort: 8080
{{ end }}
